### ISSUE TITLE
Update core prosemirror dependencies to work with latest prosemirror-view

### ISSUE THREAD

**Issue by krmayer** [ProseMirror/prosemirror-tables#203] opened 2023-07-18 17:41 UTC
I believe that prosemirror-view (1.29.1) introduced a breaking change to the decoration handler in this repo. Could we possibly update the core prosemirror dependencies for this package?

- [This commit](https://github.com/ProseMirror/prosemirror-view/commit/c3d3ccdc3477360c11e7d00254ffe33537a3e8c7) to prosemirror-view causes [columnResizing.handleDecorations](https://github.com/ProseMirror/prosemirror-tables/blob/324a97ea31bf03a4e4b294a055128727ea3a89e8/src/columnresizing.ts#L382) to throw because it is creating an invalid DecorationSet using an older prosemirror-view (1.13.3)

**Comment by ocavue** [comment] 2023-07-20 06:46
I guess you have two different versions of `prosemirror-view` installed in your project. Could you check your lock file (e.g. `yarn.lock`)? 

I'll close this issue for now since I don't see anything that should be done in prosemirror-tables, but I'll be happy to re-open it if you can provide a minimal repo to reproduce this runtime crash issue.

**Closed by ocavue** 2023-07-20 06:46 UTC
